---
configuration:
- key: "launchUrl"
  value: "App1"
- key: "ApplicationId"
  value: ""
id: null
name: "App"
artifactTypeId: "iOS App"
description:
  title: ""
  details: "App"
  icon: null
  background: null
  moreInfo: ""
  other: null
created: null
modified: null
features: null
application: null
source:
  url: "App1"
  type: "Github"
